### ISSUE TITLE
arguments to random.uniform have no effect (with further implications) 

### ISSUE THREAD

**Issue by wielandbrendel** [andersbll/cudarray#12]
I noticed that the arguments low and high to random.uniform have no effect. While it is easy to get around this limitation, the bug is grounded in a more serious problem that prevents me from implementing numpy.random.poisson in cudarray: in random.cu a cuda kernel operating directly on the output array (like kernel_stretch) seems to have no effect on the output array.

Any help is highly appreciated!
Wieland

**Comment by wielandbrendel** [comment]
The problem is related to the compile flag -arch=sm_35, which assumes compute capability 3.5, whereas I was running cudarray with compute capability 2.0. Changing to -arch=sm_20 did the trick. Maybe you could make this an environmental argument so that users can more easily match the compilation to their architecture (like you did with cudnn)?

**Comment by andersbll** [comment]
Great job finding the culprit! I'll be sure to add sm_20 as target
architecture as soon as I get better.
