### ISSUE TITLE
how cudarray is different from other works?

### ISSUE THREAD

**Issue by hainm** [andersbll/cudarray#16]
hi,

I've read the technical report here http://www2.compute.dtu.dk/~abll/pubs/larsen2014cudarray.pdf

you listed several packages but I am not so sure how cudarray vs other? and why cudarray? which features cudarray have but others don't? ...

thanks

Hai

**Comment by andersbll** [comment]
CUDArray is a drop-in replacement for NumPy which only CUDAMat/Gnumpy do in a similar manner. However, CUDAMat is limited in flexibility as it only supports matrices of type float. Moreover, the CUDAMat codebase is not so flexible as it  uses ctypes instead of Cython.

**Comment by hainm** [comment]
thanks. So I have a reason to start looking at `cudarray` now. But still need to figure out how to complie `libcudarray` without error first. (I've been using cython for my projects, so +1).

Hai
