### ISSUE TITLE
cudaarray installation problem 

### ISSUE THREAD

**Issue by malzantot** [andersbll/cudarray#18]
Hi,

I am trying to install "cudarray" but I am facing a problem.

After doing `make` and `make install` when I tried to do `python setup.py install`, I get the following error : 
`./cudarray/wrap/array_data.cpp:1384:53: fatal error: arithmetic on a pointer to
      void
    __pyx_v_self->dev_ptr = (__pyx_v_owner->dev_ptr + (__pyx_v_offset * ...`

I am using Mac OS X 10.10.3 and GCC (Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn) ,  I also have the Nvidia compiler nvcc installed using the following version : 

`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Mon_Feb_16_23:23:36_CST_2015
Cuda compilation tools, release 7.0, V7.0.27`

**Comment by andersbll** [comment]
Hi, it seems Clang is more pedantic about void * arithmetic. In [array_data.pyx](https://github.com/andersbll/cudarray/blob/master/cudarray/wrap/array_data.pyx#L18), try changing 

    self.dev_ptr = owner.dev_ptr + offset*dtype.itemsize
to

    self.dev_ptr = (<char *> owner.dev_ptr) + offset*dtype.itemsize

**Comment by malzantot** [comment]
Thanks a lot , this solved my issue. ! 

I submitted a pull request for that, please accept it.

**Comment by andersbll** [comment]
Great, I'll be sure to commit the fix.

**Comment by andersbll** [comment]
Great. I have merged the PR.
