### ISSUE TITLE
Bounds check ? 

### ISSUE THREAD

**Issue by DmitryUlyanov** [andersbll/cudarray#24]
Looks like I can access the values in the array, which are not there.

``` 
t.shape
(81920, 10)
```
and no errors when doing `t[:,10]` or `t[:,1000]`.

**Comment by andersbll** [comment]
CUDArray has very little error handling! I encourage you to develop using the NumPy backend and switch to CUDArray when it works! :)

**Comment by DmitryUlyanov** [comment]
Thank you!
