### ISSUE TITLE
 The function requires a feature absent from the GPU

### ISSUE THREAD

**Issue by mrzl** [andersbll/cudarray#37]
Hey,
just wondering if anybody came across this problem:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  ./include/cudarray/nnet/cudnn.hpp:107: The function requires a feature absent from the GPU
Aborted (core dumped)
```

I've traced it down to be coming from here: https://github.com/andersbll/neural_artistic_style/blob/master/style_network.py#L99

I'm on Ubuntu 14.04 with a fairly dated GeForce GTX 560.. I suppose that's the reason, though a new card is not an option for me at the moment and I am wondering whether it's possible to get rid of that one feature that's absent from the GPU, though I can't tell which one it would be. Do you have more insight into this?

Thanks already,
Marcel

**Comment by andersbll** [comment]
I think you are right, the GPU might be too old for cuDNN. You can avoid using cuDNN by setting the environment variable `CUDNN_ENABLED` to `0` before installation.
