### ISSUE TITLE
ImportError: No module named conv_bc01

### ISSUE THREAD

**Issue by grinya-mipt** [andersbll/cudarray#38]
Ubuntu 14.04 LTS. CUDA 7.5.
However, I installed cudarray without cuda support.
And after installation I got:

grinya@mypc:~/cudarray$ python
import cudarray
CUDArray: CUDA back-end not available, using NumPy.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cudarray/__init__.py", line 40, in <module>
    from .numpy_backend import *
  File "cudarray/numpy_backend/__init__.py", line 2, in <module>
    from .nnet import *
  File "cudarray/numpy_backend/nnet/__init__.py", line 3, in <module>
    from .conv_bc01 import *
ImportError: No module named conv_bc01 

But the file in the directory "cudarray/numpy_backend/nnet" does exist. I do not understand this error.

**Comment by andersbll** [comment]
Could the installation have failed? I assume you have run `python setup.py --without-cuda install`. Make sure a recent version of Cython is installed.

**Comment by grinya-mipt** [comment]
I do not think so, because during installation there were no errors.
Yes, I used `sudo python setup.py --without-cuda install`.
I have latest Cython. Version 0.23.4

**Comment by andersbll** [comment]
Ok, I'll try it out then! :)

**Comment by grinya-mipt** [comment]
Here is a [log](https://github.com/andersbll/cudarray/files/108980/log.txt)  of installation

**Comment by andersbll** [comment]
Thanks for the info, I can't reproduce the error. Try uninstalling CUDArray with `pip uninstall cudarray` (try multiple times to make sure all installations are removed). Then clean temporary CUDArray files with `python setup.py clean`. Finally, try installing again. If this doesn't work, you might want to try another Python distribution. I recommend Anaconda Python.

**Comment by grinya-mipt** [comment]
Well, I used Anaconda Python 2.7.
`pip uninstall cudarray` tells that `Cannot uninstall requirement cudarray, not installed`
Just tried reinstalling after `python setup.py clean`. The same problem.

**Comment by andersbll** [comment]
I see! Can you try installing without `sudo`?

**Comment by grinya-mipt** [comment]
Oh, smth different. At least I can see my Anaconda path in log:
grinya@grinyamipt:~/cudarray$ python setup.py --without-cuda install
/home/grinya/anaconda2/lib/python2.7/site-packages/setuptools-19.2-py2.7.egg/setuptools/dist.py:284: UserWarning: Normalizing '0.1.dev' to '0.1.dev0'
running install
running bdist_egg
running egg_info
writing requirements to cudarray.egg-info/requires.txt
error: [Errno 13] Permission denied: 'cudarray.egg-info/requires.txt'

**Comment by andersbll** [comment]
This is probably because the previous installation was with `sudo`. Make sure to uninstall CUDArray first (uninstall with `sudo`, that is).

**Comment by grinya-mipt** [comment]
Oh. Tried as you said. The same problem. Here is [log](https://github.com/andersbll/cudarray/files/109032/log2.txt)

**Comment by grinya-mipt** [comment]
I do not understand, but running python from a different directory (instead of cudarray's directory) works fine. And there is no ImportError =)

**Comment by andersbll** [comment]
Great! The reason why it didn't work was because Python tried to import cudarray from your working directory. This failed as the cythonized files are stored in a separate build directory. Another time If you want to store cythonized files along with your python code you should install with `python setup.py develop`.

**Comment by grinya-mipt** [comment]
Thank you!
