### ISSUE TITLE
missing vtable error when doing make

### ISSUE THREAD

**Issue by totopia** [andersbll/cudarray#44]
I got following error when doing make on MacOS. is it related to the C++ compiler?
I installed Cuda 7.5 on top of Xcode 6.2 for Mac OS 10.10, all the checks passed for Cuda Installation instructions.

/usr/bin/cc --version
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2014 NVIDIA Corporation
Built on Thu_Jul_17_19:13:24_CDT_2014
Cuda compilation tools, release 6.5, V6.5.12

NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >", referenced from:
      cudarray::cuda_kernel_check(char const*, int) in pool_b01.o
      cudarray::cuda_kernel_check(char const*, int) in array_ops.o
      cudarray::cuda_check(cudaError, char const*, int) in array_ops.o
      cudarray::cuda_check(cudaError, char const*, int) in reduction.o
      cudarray::curand_check(curandStatus, char const*, int) in random.o
      cudarray::cuda_kernel_check(char const*, int) in img2win.o
      cudarray::cuda_kernel_check(char const*, int) in rescale.o
      ...
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: fatal error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [build/libcudarray.so] Error 1

**Comment by totopia** [comment]
Never mind, this was a cud compatibility issue with mac

**Comment by andersbll** [comment]
I'm happy you got it working!
