### ISSUE TITLE
mkdir error in building libcudarray

### ISSUE THREAD

**Issue by nresnick** [andersbll/cudarray#49]
I'm getting this error:

`mkdir -p ./build`
`make: mkdir: No such file or directory`
`make: *** [build/libcudarray.so] Error 1`

Any ideas? Thanks!

**Update:** I fixed this just by doing `/bin/mkdir`, but now it's saying:

`ld: library not found for -lcudnn` ?

**Comment by andersbll** [comment]
Hi, are you on Linux? Do you call `make` in the CUDArray root directory?

**Comment by nresnick** [comment]
Nope, Mac OS X. I had to download the cuDDN libraries separately and add them to the `cud/lib/` directory. All set on that front! 

New issue though: in `python setup.py install` I'm getting

`ImportError: No module named Cython.Build`

Yet when I run `from Cython.Build import cythonize` in the IPython console directly it works (doing this through anaconda). Any ideas?

**Comment by andersbll** [comment]
Haven't seen that before. What version of Cython do you have installed? It might be outdated.

**Comment by nresnick** [comment]
Yep, had to update Cython. Now having yet another issue that someone already asked you [here](https://github.com/andersbll/cudarray/issues/34). I responded to that thread so I will close this one. Thank you for the quite replies, I really appreciate it.
