### ISSUE TITLE
fatal error: 'numpy/arrayobject.h' file not found

### ISSUE THREAD

**Issue by AnnaMag** [andersbll/cudarray#52]
running the non Cuda back-end setup install produces:

cudarray/numpy_backend/nnet/conv_bc01.c:274:10: fatal error: 'numpy/arrayobject.h' file not found
#include "numpy/arrayobject.h"
         ^
1 error generated.
error: command 'clang' failed with exit status 1

Any insights as to what might be happening?

**Comment by AnnaMag** [comment]
ad-hoc solution that made it work is to add numpy headers to the CFLAGS:

export CFLAGS="-I /usr/local/lib/python2.7/site-packages/numpy/core/include $CFLAGS"
works.

Any more formal work-around?

**Comment by ricardojmendez** [comment]
Confirmed that the work-around works. I got this issue while numpy was properly installed, and after confirming that numpy.get_include() was returning the right folder.

**Comment by yarodevuci** [comment]
did not worked for me
