### ISSUE TITLE
Install not working on OS X

### ISSUE THREAD

**Issue by elyase** [andersbll/cudarray#7]
I clone the project, then:
```bash
~/D/cudarray master ❯ make
g++ -O3 -fPIC -Wall -Wfatal-errors -I./include -I/usr/local/cuda/include -c -o src/nnet/conv_bc01_matmul.o src/nnet/conv_bc01_matmul.cpp
In file included from src/nnet/conv_bc01_matmul.cpp:1:
./include/cudarray/common.hpp:8:10: fatal error: 'cuda_runtime_api.h' file not
      found
#include <cuda_runtime_api.h>
         ^
1 error generated.
make: *** [src/nnet/conv_bc01_matmul.o] Error 1
```

**Comment by andersbll** [comment]
It can't find the CUDA header files. Make sure the CUDA path is set to where the CUDA SDK is installed. If you don't want CUDA acceleration you should [install without CUDA](https://github.com/andersbll/cudarray#without-cuda-back-end).

**Comment by elyase** [comment]
Oh thanks that worked! I somehow assumed that you also had to do `make install` without CUDA.

**Comment by andersbll** [comment]
Ok, I'll add to the 'Without CUDA' installation description that you don't have to build libcudarray. :)

**Comment by elyase** [comment]
I think it is already clear enough but may be it will save blind people like me some time,:-) Thanks!

**Comment by elyase** [comment]
Some what off-topic but do you get high CPU usage in deeppy? I get 138% in my quad-core.

**Comment by andersbll** [comment]
Make sure that Numpy's matrix multiplication operations are parallelized. If you are running the convolution examples you will get poor multi-core performance because the convolution code is not yet parallelized.

**Comment by nresnick** [comment]
How long should the convent_cifar example take without CUDA?
