### ISSUE TITLE
installation errors

### ISSUE THREAD

**Issue by zhizhengwu** [andersbll/cudarray#8]
Hi there,

Thanks for making such a great library. I am trying to install it but failed. Below are the errors:

1. in the 'make' step:
g++ -O3 -fPIC -Wall -Wfatal-errors -I./include -I/opt/cuda-5.0.35/include -c -o src/blas.o src/blas.cpp
src/blas.cpp: In function ‘const char* cudarray::cublas_message(cublasStatus_t)’:
src/blas.cpp:168: error: ‘CUBLAS_STATUS_NOT_SUPPORTED’ was not declared in this scope
compilation terminated due to -Wfatal-errors.
make: *** [src/blas.o] Error 1

g++ -O3 -fPIC -Wall -Wfatal-errors -I./include -I/opt/cuda-5.0.35/include -c -o src/blas.o src/blas.cpp
src/blas.cpp: In function ‘const char* cudarray::cublas_message(cublasStatus_t)’:
src/blas.cpp:170: error: ‘CUBLAS_STATUS_LICENSE_ERROR’ was not declared in this scope
compilation terminated due to -Wfatal-errors.
make: *** [src/blas.o] Error 1

To pass this step, I commented the four lines in blas.cpp:
//    case CUBLAS_STATUS_NOT_SUPPORTED:
//     return "The functionnality requested is not supported.";
//    case CUBLAS_STATUS_LICENSE_ERROR:
//      return "The functionality requested requires some license.";

Then I can compile the library successfully.

2. in python setup.py install --user (i don't have sudo permission)
gcc: cudarray/numpy_backend/nnet/conv_bc01.c: No such file or directory
gcc: no input files
error: command 'gcc' failed with exit status 1
I have no idea of how to solve them.

Could you please help with above errors?

Thanks.

**Comment by andersbll** [comment]
The first errors regarding the cuBLAS status messages may be caused by an old version of cuBLAS.

Regarding the second error: It may be a Cython problem. Can you install without CUDA? What version of Cython are you using? How is your Python installation - are you using Anaconda?

Best,
Anders

**Comment by zhizhengwu** [comment]
Thanks for reply.

There are still errors by installing without CUDA.
The version of cython is 0.21.2.  Python version: 2.6.6
I am not using Anaconda. Any idea?

Error compiling Cython file:
------------------------------------------------------------
...
from __future__ import absolute_import
                      ^
------------------------------------------------------------

Cython/Plex/Scanners.pxd:1:23: future feature absolute_import is not defined

Error compiling Cython file:
------------------------------------------------------------
...
#
#   Scanning an input stream
#
#=======================================================================

from __future__ import absolute_import
                      ^
------------------------------------------------------------

Cython/Plex/Scanners.py:10:23: future feature absolute_import is not defined
Compilation failed
Compiling module Cython.Plex.Actions ...
Compiling module Cython.Compiler.Lexicon ...


Regards,
Zhizheng

**Comment by andersbll** [comment]
Upgrade to Python 2.7. I wholeheartedly recommend the Anaconda Python distribution.

**Comment by andersbll** [comment]
Closed due to inactivity. Feel free to reopen.

**Comment by cxfneo** [comment]
Hi  anderabll
       I am trying to install it ,but it failed.  
python setup.py install 
error in cudarray setup command: CUDA back-end wants to be able to remove cudarray.cudarray_wrap, but the distribution doesn't contain any packages or modules under cudarray.cudarray_wrap

Could you help me,  thank you very much

**Comment by cxfneo** [comment]
I update the setup.py. Now another problem is ：
“”running build_ext
building 'cudarray.numpy_backend.nnet.conv_bc01' extension
gcc -std=gnu99 -fno-strict-aliasing -g -O2 -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include/python2.7 -c cudarray/numpy_backend/nnet/conv_bc01.c -o build/temp.linux-x86_64-2.7/cudarray/numpy_backend/nnet/conv_bc01.o
gcc: cudarray/numpy_backend/nnet/conv_bc01.c: No such file or directory
“”
I am not familiar with cpython and I indeed could not find cudarray/numpy_backend/nnet/conv_bc01.c. Is the conv_bc01.c generated by compling the code at the first step "make"?

The version of cython is 0.22 Python version: 2.7
